import random
import time
import os
import keyboard
foo = "."
pix = ""
stage = 0
delay = 0.003

def create_space_rock():
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
    while foo == ".":
        if keyboard.is_pressed("a"):
            for i in range(1):
                shd = random.randint(0, 1)
                os.system("cls")
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                time.sleep(delay)
                os.system("cls")
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, shd, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, shd, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, shd, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, shd, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                time.sleep(delay)
                os.system("cls")
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                time.sleep(delay)
                os.system("cls")
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, shd, shd, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, shd, shd, shd, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, shd, shd, shd, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, shd, shd, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                time.sleep(delay)
                os.system("cls")
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, shd, shd, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, shd, shd, shd, shd, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, shd, shd, shd, shd, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, shd, shd, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                time.sleep(delay)
                os.system("cls")
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo) # m
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, shd, shd, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, shd, shd, shd, shd, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, shd, shd, shd, shd, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, shd, shd, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                time.sleep(delay)
                os.system("cls")
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                time.sleep(delay)
                os.system("cls")
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                time.sleep(delay)
                os.system("cls")
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                time.sleep(delay)
                os.system("cls")
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                time.sleep(delay)
                os.system("cls")
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                time.sleep(delay)
        if keyboard.is_pressed("b"):
                        for i in range(1):
                            os.system("cls")
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            time.sleep(delay)
                            os.system("cls")
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            time.sleep(delay)
                            os.system("cls")
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, shd, shd, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, shd, pix, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            time.sleep(delay)
                            os.system("cls")
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, shd, shd, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, shd, shd, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            time.sleep(delay)
                            os.system("cls")
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, shd, shd, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, shd, shd, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            time.sleep(delay)
                            os.system("cls")
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo) # m
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, shd, shd, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, shd, shd, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, shd, shd, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            time.sleep(delay)
                            os.system("cls")
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            time.sleep(delay)
                            os.system("cls")
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            time.sleep(delay)
                            os.system("cls")
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            time.sleep(delay)
                            os.system("cls")
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            time.sleep(delay)
                            os.system("cls")
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, pix, pix, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, pix, pix, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            print(foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo, foo)
                            time.sleep(delay)
